---
- hosts: webservers
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enable: True
    - name: Deploy Static Website
      copy:
        src: index.html
        dest: /var/www/html/